/**
 * Entity catalog — the source of truth for every desktop screen.
 *
 * Add a column to a table, add a line here, and the list view, the filters,
 * the record form and the API all pick it up. No screen code to write.
 * Anything an admin changes under Setup → Screens is stored in meta_fields
 * and wins over what is written here.
 *
 * F(column, label, control, opts)
 *   control: text | textarea | number | integer | currency | date | toggle
 *            select | ref | readonly | url | email | phone
 *   opts: { req, list, order, w, section, form, ref, list_key, format, help }
 *     req      required
 *     list     show as a column in the list view
 *     order    column order in the list view
 *     w        column width in px
 *     section  form section heading
 *     form     order within the form
 *     ref      entity key for a lookup to another record
 *     list_key lookup_lists key for a dropdown
 *     format   money | mileage | mono | phone | date
 */

const F = (column, label, control, opts = {}) => ({
  column_name: column,
  label,
  ui_control: control,
  data_type:
    control === 'currency' || control === 'number' ? 'number'
    : control === 'integer' ? 'integer'
    : control === 'date' ? 'date'
    : control === 'toggle' ? 'bool'
    : control === 'ref' ? 'uuid'
    : 'text',
  required: !!opts.req,
  show_in_list: !!opts.list,
  list_order: opts.order ?? 100,
  width: opts.w ?? null,
  form_section: opts.section ?? 'Details',
  form_order: opts.form ?? opts.order ?? 100,
  ref_entity: opts.ref ?? null,
  lookup_list: opts.list_key ?? null,
  format: opts.format ?? null,
  help: opts.help ?? null,
});

const AUDIT = [
  F('created_at', 'Created', 'readonly', { section: 'Record', form: 900, format: 'date' }),
  F('updated_at', 'Last updated', 'readonly', { section: 'Record', form: 901, format: 'date' }),
];

export const entities = [
  // ------------------------------------------------------------- People
  {
    key: 'employees', table: 'employees', label: 'Employee', label_plural: 'Team',
    icon: 'users', nav_group: 'People', sort_order: 10, title_column: 'full_name',
    default_sort: 'full_name asc',
    search_columns: ['full_name', 'email', 'phone', 'job_title', 'territory'],
    fields: [
      F('full_name', 'Name', 'text', { req: 1, list: 1, order: 10, w: 190, section: 'Identity', form: 10 }),
      F('role', 'Role', 'select', { list: 1, order: 20, w: 130, list_key: 'employee_role', section: 'Identity', form: 20 }),
      F('job_title', 'Title', 'text', { section: 'Identity', form: 30 }),
      F('status', 'Status', 'select', { list: 1, order: 30, w: 100, list_key: 'employee_status', section: 'Identity', form: 40 }),
      F('email', 'Email', 'email', { list: 1, order: 40, w: 200, section: 'Contact', form: 50 }),
      F('phone', 'Phone', 'phone', { list: 1, order: 50, w: 130, format: 'phone', section: 'Contact', form: 60 }),
      F('territory', 'Territory', 'text', { list: 1, order: 60, w: 130, section: 'Assignment', form: 70 }),
      F('home_location', 'Home office', 'text', { section: 'Assignment', form: 80 }),
      F('supervisor_id', 'Supervisor', 'ref', { ref: 'employees', section: 'Assignment', form: 90 }),
      F('hire_date', 'Hired', 'date', { section: 'Employment', form: 100 }),
      F('termination_date', 'Separated', 'date', { section: 'Employment', form: 110 }),
      F('dl_number', "Driver's license #", 'text', { format: 'mono', section: 'Driving', form: 120 }),
      F('dl_expiration', "License expires", 'date', { list: 1, order: 70, w: 120, section: 'Driving', form: 130 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
      ...AUDIT,
    ],
  },
  {
    key: 'licenses', table: 'licenses', label: 'License', label_plural: 'Licenses & Certifications',
    icon: 'badge', nav_group: 'People', sort_order: 20, title_column: 'name',
    default_sort: 'expiration_date asc',
    search_columns: ['name', 'license_number', 'issuing_authority', 'license_type'],
    fields: [
      F('name', 'License', 'text', { req: 1, list: 1, order: 10, w: 200, section: 'Credential', form: 10 }),
      F('license_type', 'Type', 'select', { list: 1, order: 20, w: 140, list_key: 'license_type', section: 'Credential', form: 20 }),
      F('employee_id', 'Held by', 'ref', { list: 1, order: 30, w: 160, ref: 'employees', section: 'Credential', form: 30 }),
      F('license_number', 'Number', 'text', { list: 1, order: 40, w: 140, format: 'mono', section: 'Credential', form: 40 }),
      F('issuing_authority', 'Issuer', 'text', { section: 'Credential', form: 50 }),
      F('state_jurisdiction', 'State', 'text', { section: 'Credential', form: 60 }),
      F('issue_date', 'Issued', 'date', { section: 'Dates', form: 70 }),
      F('expiration_date', 'Expires', 'date', { list: 1, order: 50, w: 110, section: 'Dates', form: 80 }),
      F('renewal_date', 'Renew by', 'date', { section: 'Dates', form: 90 }),
      F('renewal_frequency_months', 'Renewal cycle (months)', 'integer', { section: 'Dates', form: 100 }),
      F('status', 'Status', 'select', { list: 1, order: 60, w: 110, list_key: 'license_status', section: 'Credential', form: 25 }),
      F('ceu_requirement_id', 'CEU requirement', 'ref', { ref: 'ceu_requirements', section: 'Renewal', form: 110 }),
      F('ceu_hours_required', 'CEU hours required', 'number', { section: 'Renewal', form: 120 }),
      F('renewal_fee', 'Renewal fee', 'currency', { format: 'money', section: 'Renewal', form: 130 }),
      F('renewal_submitted', 'Renewal submitted', 'toggle', { section: 'Renewal', form: 140 }),
      F('renewal_paid', 'Renewal paid', 'toggle', { section: 'Renewal', form: 150 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
      ...AUDIT,
    ],
  },
  {
    key: 'ceu_records', table: 'ceu_records', label: 'CEU record', label_plural: 'CEU Records',
    icon: 'graduation', nav_group: 'People', sort_order: 30, title_column: 'course_name',
    default_sort: 'completion_date desc',
    search_columns: ['course_name', 'provider', 'category'],
    fields: [
      F('course_name', 'Course', 'text', { req: 1, list: 1, order: 10, w: 230, form: 10 }),
      F('employee_id', 'Employee', 'ref', { list: 1, order: 20, w: 160, ref: 'employees', form: 20 }),
      F('ceu_hours', 'Hours', 'number', { list: 1, order: 30, w: 80, form: 30 }),
      F('completion_date', 'Completed', 'date', { req: 1, list: 1, order: 40, w: 110, form: 40 }),
      F('category', 'Category', 'select', { list: 1, order: 50, w: 140, list_key: 'ceu_category', form: 50 }),
      F('provider', 'Provider', 'text', { list: 1, order: 60, w: 150, form: 60 }),
      F('license_id', 'Applies to license', 'ref', { ref: 'licenses', form: 70 }),
      F('expiration_date', 'Credit expires', 'date', { form: 80 }),
      F('cost', 'Cost', 'currency', { format: 'money', section: 'Cost', form: 90 }),
      F('paid_by', 'Paid by', 'text', { section: 'Cost', form: 100 }),
      F('approved_for_renewal', 'Approved for renewal', 'toggle', { form: 110 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
      ...AUDIT,
    ],
  },
  {
    key: 'ceu_requirements', table: 'ceu_requirements', label: 'CEU requirement', label_plural: 'CEU Requirements',
    icon: 'rules', nav_group: 'People', sort_order: 40, title_column: 'name',
    default_sort: 'name asc', search_columns: ['name', 'license_type', 'state_jurisdiction'],
    fields: [
      F('name', 'Requirement', 'text', { req: 1, list: 1, order: 10, w: 220, form: 10 }),
      F('license_type', 'License type', 'select', { list: 1, order: 20, w: 160, list_key: 'license_type', form: 20 }),
      F('state_jurisdiction', 'Jurisdiction', 'text', { list: 1, order: 30, w: 110, form: 30 }),
      F('credits_required', 'Credits required', 'number', { list: 1, order: 40, w: 120, form: 40 }),
      F('period_years', 'Period (years)', 'integer', { list: 1, order: 50, w: 110, form: 50 }),
      F('renewal_cycle', 'Renewal cycle', 'text', { form: 60 }),
      F('special_topics', 'Required topics', 'textarea', { form: 70 }),
      F('renewal_fee', 'Renewal fee', 'currency', { format: 'money', form: 80 }),
      F('renewal_url', 'Renewal site', 'url', { form: 90 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
      ...AUDIT,
    ],
  },

  // ------------------------------------------------------------- Fleet
  {
    key: 'vehicles', table: 'vehicles', label: 'Vehicle', label_plural: 'Fleet',
    icon: 'van', nav_group: 'Assets', sort_order: 50, title_column: 'unit_number',
    default_sort: 'unit_number asc',
    search_columns: ['unit_number', 'vin', 'plate_number', 'make', 'model'],
    fields: [
      F('unit_number', 'Unit', 'text', { req: 1, list: 1, order: 10, w: 110, section: 'Identity', form: 10 }),
      F('make', 'Make', 'text', { list: 1, order: 20, w: 100, section: 'Identity', form: 20 }),
      F('model', 'Model', 'text', { list: 1, order: 30, w: 110, section: 'Identity', form: 30 }),
      F('model_year', 'Year', 'integer', { list: 1, order: 40, w: 70, section: 'Identity', form: 40 }),
      F('vin', 'VIN', 'text', { format: 'mono', section: 'Identity', form: 50 }),
      F('plate_number', 'Plate', 'text', { list: 1, order: 50, w: 100, format: 'mono', section: 'Identity', form: 60 }),
      F('plate_state', 'Plate state', 'text', { section: 'Identity', form: 70 }),
      F('status', 'Status', 'select', { list: 1, order: 60, w: 110, list_key: 'vehicle_status', section: 'Identity', form: 15 }),
      F('primary_driver_id', 'Primary driver', 'ref', { list: 1, order: 70, w: 150, ref: 'employees', section: 'Assignment', form: 80 }),
      F('current_mileage', 'Mileage', 'integer', { list: 1, order: 80, w: 100, format: 'mileage', section: 'Service', form: 90 }),
      F('last_mileage_update', 'Mileage as of', 'readonly', { format: 'date', section: 'Service', form: 100 }),
      F('registration_expiration', 'Registration', 'date', { list: 1, order: 90, w: 115, section: 'Compliance', form: 110 }),
      F('state_inspection_due', 'State inspection', 'date', { list: 1, order: 100, w: 125, section: 'Compliance', form: 120 }),
      F('insurance_policy_id', 'Policy', 'ref', { ref: 'insurance_policies', section: 'Compliance', form: 130 }),
      F('next_oil_change_mileage', 'Next oil change (mi)', 'integer', { format: 'mileage', section: 'Service', form: 140 }),
      F('next_service_date', 'Next service', 'date', { section: 'Service', form: 150 }),
      F('purchase_date', 'Purchased', 'date', { section: 'Ownership', form: 160 }),
      F('lease_loan_info', 'Lease / loan', 'text', { section: 'Ownership', form: 170 }),
      F('fuel_card_number', 'Fuel card', 'text', { format: 'mono', section: 'Equipment', form: 180 }),
      F('toll_transponder', 'Transponder', 'text', { format: 'mono', section: 'Equipment', form: 190 }),
      F('gps_tracker_id', 'GPS tracker', 'text', { format: 'mono', section: 'Equipment', form: 200 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 300 }),
      ...AUDIT,
    ],
  },
  {
    key: 'vehicle_maintenance', table: 'vehicle_maintenance', label: 'Service record', label_plural: 'Vehicle Service',
    icon: 'wrench', nav_group: 'Assets', sort_order: 60, title_column: 'service_type',
    default_sort: 'service_date desc', search_columns: ['service_type', 'notes'],
    fields: [
      F('vehicle_id', 'Vehicle', 'ref', { req: 1, list: 1, order: 10, w: 120, ref: 'vehicles', form: 10 }),
      F('service_type', 'Service', 'select', { req: 1, list: 1, order: 20, w: 160, list_key: 'vehicle_service_type', form: 20 }),
      F('service_date', 'Date', 'date', { req: 1, list: 1, order: 30, w: 110, form: 30 }),
      F('mileage_at_service', 'Mileage', 'integer', { list: 1, order: 40, w: 100, format: 'mileage', form: 40 }),
      F('cost', 'Cost', 'currency', { list: 1, order: 50, w: 100, format: 'money', form: 50 }),
      F('vendor_id', 'Vendor', 'ref', { list: 1, order: 60, w: 150, ref: 'vendors', form: 60 }),
      F('next_service_due_date', 'Next due', 'date', { list: 1, order: 70, w: 110, form: 70 }),
      F('next_service_due_mileage', 'Next due (mi)', 'integer', { format: 'mileage', form: 80 }),
      F('warranty_applies', 'Under warranty', 'toggle', { form: 90 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
      ...AUDIT,
    ],
  },
  {
    key: 'equipment', table: 'equipment', label: 'Asset', label_plural: 'Equipment',
    icon: 'toolbox', nav_group: 'Assets', sort_order: 70, title_column: 'name',
    default_sort: 'name asc',
    search_columns: ['name', 'serial_number', 'asset_tag', 'make', 'model'],
    fields: [
      F('name', 'Asset', 'text', { req: 1, list: 1, order: 10, w: 200, section: 'Identity', form: 10 }),
      F('asset_category', 'Category', 'select', { list: 1, order: 20, w: 130, list_key: 'asset_category', section: 'Identity', form: 20 }),
      F('serial_number', 'Serial', 'text', { list: 1, order: 30, w: 150, format: 'mono', section: 'Identity', form: 30 }),
      F('asset_tag', 'Tag', 'text', { format: 'mono', section: 'Identity', form: 40 }),
      F('make', 'Make', 'text', { section: 'Identity', form: 50 }),
      F('model', 'Model', 'text', { section: 'Identity', form: 60 }),
      F('status', 'Status', 'select', { list: 1, order: 40, w: 120, list_key: 'asset_status', section: 'Identity', form: 15 }),
      F('condition', 'Condition', 'select', { list_key: 'asset_condition', section: 'Identity', form: 70 }),
      F('assigned_employee_id', 'Assigned to', 'ref', { list: 1, order: 50, w: 150, ref: 'employees', section: 'Assignment', form: 80 }),
      F('assigned_vehicle_id', 'On vehicle', 'ref', { list: 1, order: 60, w: 110, ref: 'vehicles', section: 'Assignment', form: 90 }),
      F('current_location', 'Location', 'text', { section: 'Assignment', form: 100 }),
      F('requires_calibration', 'Needs calibration', 'toggle', { section: 'Calibration', form: 110 }),
      F('calibration_interval_months', 'Interval (months)', 'integer', { section: 'Calibration', form: 120 }),
      F('last_calibration_date', 'Last calibrated', 'date', { section: 'Calibration', form: 130 }),
      F('next_calibration_due', 'Calibration due', 'date', { list: 1, order: 70, w: 125, section: 'Calibration', form: 140 }),
      F('purchase_date', 'Purchased', 'date', { section: 'Financial', form: 150 }),
      F('purchase_price', 'Price', 'currency', { format: 'money', section: 'Financial', form: 160 }),
      F('warranty_expiration', 'Warranty ends', 'date', { section: 'Financial', form: 170 }),
      F('vendor_id', 'Vendor', 'ref', { ref: 'vendors', section: 'Financial', form: 180 }),
      F('insurance_policy_id', 'Policy', 'ref', { ref: 'insurance_policies', section: 'Financial', form: 190 }),
      F('expected_useful_life_years', 'Useful life (yrs)', 'integer', { section: 'Replacement', form: 200 }),
      F('replacement_target_date', 'Replace by', 'date', { section: 'Replacement', form: 210 }),
      F('estimated_replacement_cost', 'Replacement cost', 'currency', { format: 'money', section: 'Replacement', form: 220 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 300 }),
      ...AUDIT,
    ],
  },
  {
    key: 'maintenance_records', table: 'maintenance_records', label: 'Calibration record', label_plural: 'Calibration & Service',
    icon: 'gauge', nav_group: 'Assets', sort_order: 80, title_column: 'service_type',
    default_sort: 'service_date desc', search_columns: ['service_type', 'performed_by', 'result_notes'],
    fields: [
      F('equipment_id', 'Asset', 'ref', { req: 1, list: 1, order: 10, w: 190, ref: 'equipment', form: 10 }),
      F('service_type', 'Type', 'select', { req: 1, list: 1, order: 20, w: 140, list_key: 'equipment_service_type', form: 20 }),
      F('service_date', 'Date', 'date', { req: 1, list: 1, order: 30, w: 110, form: 30 }),
      F('passed', 'Passed', 'toggle', { list: 1, order: 40, w: 90, form: 40 }),
      F('performed_by', 'Performed by', 'text', { list: 1, order: 50, w: 150, form: 50 }),
      F('vendor_id', 'Vendor', 'ref', { ref: 'vendors', form: 60 }),
      F('cost', 'Cost', 'currency', { format: 'money', form: 70 }),
      F('next_due_date', 'Next due', 'date', { list: 1, order: 60, w: 110, form: 80,
        help: 'Saving this pushes the new due date onto the asset automatically.' }),
      F('result_notes', 'Result', 'textarea', { form: 90 }),
      ...AUDIT,
    ],
  },
  {
    key: 'supplies', table: 'supplies', label: 'Supply item', label_plural: 'Supplies',
    icon: 'boxes', nav_group: 'Assets', sort_order: 90, title_column: 'item_name',
    default_sort: 'item_name asc', search_columns: ['item_name', 'sku', 'category', 'storage_location'],
    fields: [
      F('item_name', 'Item', 'text', { req: 1, list: 1, order: 10, w: 210, form: 10 }),
      F('category', 'Category', 'select', { list: 1, order: 20, w: 140, list_key: 'supply_category', form: 20 }),
      F('sku', 'SKU', 'text', { format: 'mono', form: 30 }),
      F('quantity_on_hand', 'On hand', 'number', { list: 1, order: 30, w: 90, form: 40 }),
      F('reorder_point', 'Reorder at', 'number', { list: 1, order: 40, w: 95, form: 50 }),
      F('reorder_quantity', 'Reorder qty', 'number', { form: 60 }),
      F('target_quantity', 'Target', 'number', { form: 70 }),
      F('unit_of_measure', 'Unit', 'text', { form: 80 }),
      F('unit_cost', 'Unit cost', 'currency', { list: 1, order: 50, w: 95, format: 'money', form: 90 }),
      F('vendor_id', 'Vendor', 'ref', { list: 1, order: 60, w: 150, ref: 'vendors', form: 100 }),
      F('storage_location', 'Location', 'text', { list: 1, order: 70, w: 130, form: 110 }),
      F('lot_number', 'Lot', 'text', { format: 'mono', section: 'Lot control', form: 120 }),
      F('expiration_date', 'Lot expires', 'date', { list: 1, order: 80, w: 110, section: 'Lot control', form: 130 }),
      F('last_count_date', 'Last counted', 'date', { section: 'Lot control', form: 140 }),
      F('product_url', 'Product link', 'url', { form: 150 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
      ...AUDIT,
    ],
  },
  {
    key: 'inventory_transactions', table: 'inventory_transactions', label: 'Inventory movement', label_plural: 'Inventory Ledger',
    icon: 'ledger', nav_group: 'Assets', sort_order: 95, title_column: 'txn_type',
    default_sort: 'occurred_at desc', search_columns: ['reference', 'notes'],
    fields: [
      F('supply_id', 'Item', 'ref', { req: 1, list: 1, order: 10, w: 200, ref: 'supplies', form: 10 }),
      F('txn_type', 'Movement', 'select', { req: 1, list: 1, order: 20, w: 110, list_key: 'inventory_txn_type', form: 20 }),
      F('quantity', 'Qty', 'number', { req: 1, list: 1, order: 30, w: 80, form: 30,
        help: 'Negative for issues and waste. A Count sets the on-hand figure outright.' }),
      F('occurred_at', 'When', 'date', { list: 1, order: 40, w: 130, form: 40 }),
      F('employee_id', 'Employee', 'ref', { list: 1, order: 50, w: 150, ref: 'employees', form: 50 }),
      F('vehicle_id', 'Vehicle', 'ref', { list: 1, order: 60, w: 100, ref: 'vehicles', form: 60 }),
      F('vendor_id', 'Vendor', 'ref', { ref: 'vendors', form: 70 }),
      F('unit_cost', 'Unit cost', 'currency', { format: 'money', form: 80 }),
      F('reference', 'Reference', 'text', { list: 1, order: 70, w: 140, form: 90 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
    ],
  },

  // ------------------------------------------------------------- Business
  {
    key: 'vendors', table: 'vendors', label: 'Vendor', label_plural: 'Vendors',
    icon: 'store', nav_group: 'Business', sort_order: 100, title_column: 'name',
    default_sort: 'name asc', search_columns: ['name', 'contact_name', 'email', 'phone', 'category'],
    fields: [
      F('name', 'Vendor', 'text', { req: 1, list: 1, order: 10, w: 200, form: 10 }),
      F('category', 'Category', 'select', { list: 1, order: 20, w: 150, list_key: 'vendor_category', form: 20 }),
      F('contact_name', 'Contact', 'text', { list: 1, order: 30, w: 150, form: 30 }),
      F('phone', 'Phone', 'phone', { list: 1, order: 40, w: 130, format: 'phone', form: 40 }),
      F('email', 'Email', 'email', { list: 1, order: 50, w: 200, form: 50 }),
      F('website', 'Website', 'url', { form: 60 }),
      F('account_number', 'Account #', 'text', { format: 'mono', form: 70 }),
      F('payment_terms', 'Terms', 'text', { list: 1, order: 60, w: 100, form: 80 }),
      F('preferred', 'Preferred', 'toggle', { list: 1, order: 70, w: 100, form: 90 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
      ...AUDIT,
    ],
  },
  {
    key: 'insurance_policies', table: 'insurance_policies', label: 'Policy', label_plural: 'Insurance',
    icon: 'shield', nav_group: 'Business', sort_order: 110, title_column: 'name',
    default_sort: 'expiration_date asc', search_columns: ['name', 'policy_number', 'carrier', 'policy_type'],
    fields: [
      F('name', 'Policy', 'text', { req: 1, list: 1, order: 10, w: 200, form: 10 }),
      F('policy_type', 'Type', 'select', { list: 1, order: 20, w: 150, list_key: 'policy_type', form: 20 }),
      F('carrier', 'Carrier', 'text', { list: 1, order: 30, w: 160, form: 30 }),
      F('policy_number', 'Number', 'text', { list: 1, order: 40, w: 150, format: 'mono', form: 40 }),
      F('effective_date', 'Effective', 'date', { list: 1, order: 50, w: 110, form: 50 }),
      F('expiration_date', 'Expires', 'date', { list: 1, order: 60, w: 110, form: 60 }),
      F('premium_amount', 'Premium', 'currency', { list: 1, order: 70, w: 110, format: 'money', form: 70 }),
      F('broker_vendor_id', 'Broker', 'ref', { ref: 'vendors', form: 80 }),
      F('status', 'Status', 'select', { list_key: 'generic_status', form: 25 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
      ...AUDIT,
    ],
  },
  {
    key: 'claims_incidents', table: 'claims_incidents', label: 'Incident', label_plural: 'Claims & Incidents',
    icon: 'alert', nav_group: 'Business', sort_order: 120, title_column: 'incident_number',
    default_sort: 'incident_date desc',
    search_columns: ['incident_number', 'claim_number', 'description', 'incident_type'],
    fields: [
      F('incident_number', 'Incident #', 'text', { req: 1, list: 1, order: 10, w: 130, format: 'mono', form: 10 }),
      F('incident_type', 'Type', 'select', { list: 1, order: 20, w: 140, list_key: 'incident_type', form: 20 }),
      F('incident_date', 'Date', 'date', { req: 1, list: 1, order: 30, w: 110, form: 30 }),
      F('status', 'Status', 'select', { list: 1, order: 40, w: 120, list_key: 'claim_status', form: 40 }),
      F('employee_id', 'Employee', 'ref', { list: 1, order: 50, w: 150, ref: 'employees', form: 50 }),
      F('vehicle_id', 'Vehicle', 'ref', { list: 1, order: 60, w: 100, ref: 'vehicles', form: 60 }),
      F('equipment_id', 'Asset', 'ref', { ref: 'equipment', form: 70 }),
      F('policy_id', 'Policy', 'ref', { ref: 'insurance_policies', form: 80 }),
      F('claim_number', 'Claim #', 'text', { format: 'mono', form: 90 }),
      F('cost_reserve', 'Reserve', 'currency', { list: 1, order: 70, w: 110, format: 'money', form: 100 }),
      F('description', 'What happened', 'textarea', { form: 110 }),
      F('resolution', 'Resolution', 'textarea', { form: 120 }),
      F('follow_up_needed', 'Follow-up needed', 'toggle', { form: 130 }),
      F('follow_up_date', 'Follow up on', 'date', { form: 140 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
      ...AUDIT,
    ],
  },
  {
    key: 'software_subscriptions', table: 'software_subscriptions', label: 'Subscription', label_plural: 'Software',
    icon: 'app', nav_group: 'Business', sort_order: 130, title_column: 'service_name',
    default_sort: 'renewal_date asc', search_columns: ['service_name', 'category'],
    fields: [
      F('service_name', 'Service', 'text', { req: 1, list: 1, order: 10, w: 180, form: 10 }),
      F('category', 'Category', 'text', { list: 1, order: 20, w: 140, form: 20 }),
      F('vendor_id', 'Vendor', 'ref', { list: 1, order: 30, w: 150, ref: 'vendors', form: 30 }),
      F('cost', 'Cost', 'currency', { list: 1, order: 40, w: 100, format: 'money', form: 40 }),
      F('billing_frequency', 'Billing', 'select', { list: 1, order: 50, w: 110, list_key: 'billing_frequency', form: 50 }),
      F('seats', 'Seats', 'integer', { list: 1, order: 60, w: 80, form: 60 }),
      F('renewal_date', 'Renews', 'date', { list: 1, order: 70, w: 110, form: 70 }),
      F('status', 'Status', 'select', { list_key: 'generic_status', form: 15 }),
      F('account_owner_id', 'Owner', 'ref', { list: 1, order: 80, w: 140, ref: 'employees', form: 80 }),
      F('login_url', 'Login', 'url', { form: 90 }),
      F('credential_vault_ref', 'Vault entry', 'text', { form: 100,
        help: 'Name of the entry in your password manager. Never store the password itself here.' }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
      ...AUDIT,
    ],
  },
  {
    key: 'sops', table: 'sops', label: 'SOP', label_plural: 'SOPs & Checklists',
    icon: 'doc', nav_group: 'Business', sort_order: 140, title_column: 'title',
    default_sort: 'title asc', search_columns: ['title', 'category', 'body'],
    fields: [
      F('title', 'Title', 'text', { req: 1, list: 1, order: 10, w: 260, form: 10 }),
      F('category', 'Category', 'text', { list: 1, order: 20, w: 150, form: 20 }),
      F('version', 'Version', 'text', { list: 1, order: 30, w: 90, format: 'mono', form: 30 }),
      F('effective_date', 'Effective', 'date', { list: 1, order: 40, w: 110, form: 40 }),
      F('owner_id', 'Owner', 'ref', { list: 1, order: 50, w: 150, ref: 'employees', form: 50 }),
      F('last_updated_by_id', 'Updated by', 'ref', { ref: 'employees', form: 60 }),
      F('body', 'Content', 'textarea', { form: 70 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 200 }),
      ...AUDIT,
    ],
  },

  // -------------------------------------------------------------- Radon
  {
    key: 'radon_tests', table: 'radon_tests', label: 'Radon set', label_plural: 'Radon Sets',
    icon: 'gauge', nav_group: 'Radon', sort_order: 150, title_column: 'property_address',
    default_sort: 'deployed_at desc',
    search_columns: ['test_number', 'property_address', 'client_name', 'isn_order_id', 'lab_report_number'],
    fields: [
      F('test_number', 'Set #', 'text', { list: 1, order: 10, w: 130, format: 'mono', section: 'Job', form: 10 }),
      F('property_address', 'Property', 'text', { req: 1, list: 1, order: 20, w: 240, section: 'Job', form: 20 }),
      F('property_city', 'City', 'text', { section: 'Job', form: 30 }),
      F('property_state', 'State', 'text', { section: 'Job', form: 40 }),
      F('property_zip', 'ZIP', 'text', { section: 'Job', form: 50, format: 'mono' }),
      F('foundation_type', 'Foundation', 'select', { list_key: 'radon_foundation', section: 'Job', form: 60 }),
      F('isn_order_id', 'ISN order', 'text', { list: 1, order: 30, w: 110, format: 'mono', section: 'Job', form: 70,
        help: 'The order number in Inspection Support. This is the link back to the job.' }),
      F('isn_order_url', 'ISN link', 'url', { section: 'Job', form: 80 }),
      F('client_name', 'Client', 'text', { section: 'Client', form: 90 }),
      F('client_phone', 'Client phone', 'phone', { section: 'Client', form: 100, format: 'phone' }),
      F('client_email', 'Client email', 'email', { section: 'Client', form: 110 }),
      F('agent_name', 'Agent', 'text', { section: 'Client', form: 120 }),

      F('status', 'Status', 'select', { list: 1, order: 40, w: 130, list_key: 'radon_test_status', section: 'Test', form: 130 }),
      F('test_method', 'Method', 'select', { list_key: 'radon_test_method', section: 'Test', form: 140 }),
      F('inspector_id', 'Placed by', 'ref', { list: 1, order: 50, w: 150, ref: 'employees', section: 'Test', form: 150 }),
      F('retrieved_by_id', 'Picked up by', 'ref', { ref: 'employees', section: 'Test', form: 160 }),
      F('scheduled_for', 'Scheduled', 'date', { section: 'Test', form: 170 }),
      F('deployed_at', 'Placed', 'date', { list: 1, order: 60, w: 120, section: 'Test', form: 180 }),
      F('retrieved_at', 'Picked up', 'date', { section: 'Test', form: 190 }),
      F('hours_deployed', 'Hours out', 'number', { section: 'Test', form: 200 }),
      F('closed_house_start', 'Closed house since', 'date', { section: 'Conditions', form: 210 }),
      F('closed_house_confirmed', 'Closed-house conditions confirmed', 'toggle', { section: 'Conditions', form: 220 }),
      F('tamper_evident', 'Seals intact at pickup', 'toggle', { section: 'Conditions', form: 230 }),
      F('conditions_notes', 'Conditions notes', 'textarea', { section: 'Conditions', form: 240 }),

      F('qa_sequence_number', 'Set number for this device', 'readonly', { section: 'Quality check', form: 250 }),
      F('qa_duplicate_required', 'Duplicate required', 'toggle', { list: 1, order: 70, w: 110, section: 'Quality check', form: 260,
        help: 'Set automatically when the set lands on the interval. It cannot go out without a second device.' }),
      F('qa_reason', 'Why', 'readonly', { section: 'Quality check', form: 270 }),

      F('result_pci_l', 'Result pCi/L', 'number', { list: 1, order: 80, w: 110, section: 'Result', form: 280 }),
      F('duplicate_pci_l', 'Duplicate pCi/L', 'number', { section: 'Result', form: 290 }),
      F('rpd_pct', 'Difference %', 'readonly', { section: 'Result', form: 300,
        help: 'How far apart the two readings are. Over the tolerance and the pair gets flagged.' }),
      F('rpd_within_tolerance', 'Pair agrees', 'readonly', { section: 'Result', form: 310 }),
      F('result_status', 'Result', 'select', { section: 'Result', form: 320 }),
      F('mitigation_recommended', 'Mitigation recommended', 'toggle', { section: 'Result', form: 330 }),
      F('lab_vendor_id', 'Lab', 'ref', { ref: 'vendors', section: 'Result', form: 340 }),
      F('lab_report_number', 'Lab report #', 'text', { format: 'mono', section: 'Result', form: 350 }),
      F('report_delivered_at', 'Reported to client', 'date', { section: 'Result', form: 360 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 400 }),
      ...AUDIT,
    ],
  },
  {
    key: 'radon_deployments', table: 'radon_deployments', label: 'Device on a set',
    label_plural: 'Devices Placed', icon: 'toolbox', nav_group: 'Radon', sort_order: 160,
    title_column: 'role', default_sort: 'created_at desc',
    search_columns: ['device_serial', 'canister_lot', 'tamper_seal_number', 'placement_room'],
    fields: [
      F('radon_test_id', 'Set', 'ref', { req: 1, list: 1, order: 10, w: 200, ref: 'radon_tests', form: 10 }),
      F('role', 'Role', 'select', { req: 1, list: 1, order: 20, w: 120, list_key: 'radon_device_role', form: 20 }),
      F('equipment_id', 'Monitor', 'ref', { list: 1, order: 30, w: 170, ref: 'equipment', form: 30 }),
      F('device_serial', 'Serial', 'text', { format: 'mono', form: 40 }),
      F('canister_lot', 'Canister lot', 'text', { format: 'mono', form: 50 }),
      F('supply_id', 'From supply', 'ref', { ref: 'supplies', form: 60 }),
      F('placement_floor', 'Floor', 'select', { list: 1, order: 40, w: 110, list_key: 'radon_placement_floor', section: 'Placement', form: 70 }),
      F('placement_room', 'Room', 'text', { section: 'Placement', form: 80 }),
      F('distance_inches', 'Inches from the primary', 'number', { section: 'Placement', form: 90,
        help: 'Duplicates sit right beside the primary — a few inches apart, same height.' }),
      F('placement_notes', 'Placement notes', 'textarea', { section: 'Placement', form: 100 }),
      F('start_at', 'Started', 'date', { list: 1, order: 50, w: 120, section: 'Timing', form: 110 }),
      F('end_at', 'Ended', 'date', { section: 'Timing', form: 120 }),
      F('hours_exposed', 'Hours', 'number', { section: 'Timing', form: 130 }),
      F('tamper_seal_number', 'Seal #', 'text', { format: 'mono', section: 'Custody', form: 140 }),
      F('seal_intact', 'Seal intact', 'toggle', { section: 'Custody', form: 150 }),
      F('result_pci_l', 'Reading pCi/L', 'number', { list: 1, order: 60, w: 110, section: 'Result', form: 160 }),
      F('voided', 'Voided', 'toggle', { section: 'Result', form: 170 }),
      F('void_reason', 'Why voided', 'text', { section: 'Result', form: 180 }),
      ...AUDIT,
    ],
  },
  {
    key: 'radon_custody_events', table: 'radon_custody_events', label: 'Custody event',
    label_plural: 'Chain of Custody', icon: 'ledger', nav_group: 'Radon', sort_order: 170,
    title_column: 'event_type', default_sort: 'occurred_at desc',
    search_columns: ['party_name', 'notes'],
    fields: [
      F('radon_test_id', 'Set', 'ref', { req: 1, list: 1, order: 10, w: 200, ref: 'radon_tests', form: 10 }),
      F('event_type', 'What happened', 'select', { req: 1, list: 1, order: 20, w: 160, list_key: 'radon_custody_event', form: 20 }),
      F('occurred_at', 'When', 'date', { list: 1, order: 30, w: 150, form: 30 }),
      F('employee_id', 'Who', 'ref', { list: 1, order: 40, w: 150, ref: 'employees', form: 40 }),
      F('party_name', 'Handed to', 'text', { list: 1, order: 50, w: 150, form: 50 }),
      F('deployment_id', 'Which device', 'ref', { ref: 'radon_deployments', form: 60 }),
      F('gps_lat', 'Latitude', 'number', { section: 'Where', form: 70 }),
      F('gps_lng', 'Longitude', 'number', { section: 'Where', form: 80 }),
      F('signature_ref', 'Signature', 'text', { section: 'Proof', form: 90 }),
      F('photo_ref', 'Photo', 'text', { section: 'Proof', form: 100 }),
      F('notes', 'Notes', 'textarea', { section: 'Notes', form: 110 }),
    ],
  },
];

export const entityByKey = Object.fromEntries(entities.map((e) => [e.key, e]));
export default entities;
